# Generated by Django 3.1.7 on 2021-03-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyUsTitle', models.CharField(max_length=100)),
                ('whyUs1', models.CharField(max_length=100)),
                ('whyUsDesc1', models.TextField()),
                ('whyUs2', models.CharField(max_length=100)),
                ('whyUsDesc2', models.TextField()),
                ('whyUs3', models.CharField(max_length=100)),
                ('whyUsDesc3', models.TextField()),
            ],
        ),
    ]
