# Generated by Django 3.1.7 on 2021-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessertOption', models.CharField(max_length=100)),
                ('dessertContent', models.CharField(max_length=100)),
                ('dessertDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DrinksMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinksOption', models.CharField(max_length=100)),
                ('drinksContent', models.CharField(max_length=100)),
                ('drinksDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainOption', models.CharField(max_length=100)),
                ('mainContent', models.CharField(max_length=100)),
                ('mainDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StarterMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starterOption', models.CharField(max_length=100)),
                ('starterContent', models.CharField(max_length=100)),
                ('starterDesc', models.TextField()),
            ],
        ),
    ]
