# Generated by Django 3.1.7 on 2021-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_dessertmenu_drinksmenu_mainmenu_startermenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessertmenu',
            name='dessertPrice',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinksmenu',
            name='drinksPrice',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='mainPrice',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startermenu',
            name='starterPrice',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
