# Generated by Django 3.0.5 on 2021-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_openhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhours',
            name='weekdays',
        ),
        migrations.RemoveField(
            model_name='openhours',
            name='weekends',
        ),
        migrations.AddField(
            model_name='openhours',
            name='weekdays_endTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openhours',
            name='weekdays_startTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openhours',
            name='weekends_endTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openhours',
            name='weekends_startTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
