# Generated by Django 3.0.5 on 2021-03-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210326_1055'),
        ('restaurant', '0010_call_email'),
    ]

    operations = [
    ]
