# Generated by Django 3.0.5 on 2021-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_merge_20210326_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertmenu',
            name='dessertOption',
            field=models.CharField(default='Dessert', max_length=100),
        ),
        migrations.AlterField(
            model_name='drinksmenu',
            name='drinksOption',
            field=models.CharField(default='Drink', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='mainOption',
            field=models.CharField(default='Main', max_length=100),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='starterOption',
            field=models.CharField(default='Starter', max_length=100),
        ),
    ]
