# Generated by Django 3.0.5 on 2021-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20210326_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinksmenu',
            name='drinksOption',
            field=models.CharField(default='Drink', editable=False, max_length=100),
        ),
    ]
