# Generated by Django 3.0.5 on 2021-03-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20210326_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertmenu',
            name='dessertOption',
            field=models.CharField(default='Dessert', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='mainOption',
            field=models.CharField(default='Main', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='starterOption',
            field=models.CharField(default='Starter', editable=False, max_length=100),
        ),
    ]
