# Generated by Django 3.0.5 on 2021-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20210326_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinksmenu',
            name='drinksContent',
            field=models.CharField(max_length=100, verbose_name='Drink name'),
        ),
    ]
