# Generated by Django 3.0.5 on 2021-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20210326_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertmenu',
            name='dessertContent',
            field=models.CharField(max_length=100, verbose_name='Dessert name'),
        ),
        migrations.AlterField(
            model_name='dessertmenu',
            name='dessertDesc',
            field=models.TextField(verbose_name='Dessert content'),
        ),
        migrations.AlterField(
            model_name='dessertmenu',
            name='dessertPrice',
            field=models.CharField(max_length=100, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='drinksmenu',
            name='drinksDesc',
            field=models.TextField(verbose_name='Drink content'),
        ),
        migrations.AlterField(
            model_name='drinksmenu',
            name='drinksPrice',
            field=models.CharField(max_length=100, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='mainContent',
            field=models.CharField(max_length=100, verbose_name='Food name'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='mainDesc',
            field=models.TextField(verbose_name='Food content'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='mainPrice',
            field=models.CharField(max_length=100, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='starterContent',
            field=models.CharField(max_length=100, verbose_name='Starter name'),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='starterDesc',
            field=models.TextField(verbose_name='Starter content'),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='starterPrice',
            field=models.CharField(max_length=100, verbose_name='Price'),
        ),
    ]
