# Generated by Django 3.0.5 on 2021-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20210326_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutPar1',
            field=models.TextField(default='', verbose_name='About us content 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='aboutPar2',
            field=models.TextField(default='', verbose_name='About us content 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='aboutPar3',
            field=models.TextField(default='', verbose_name='About us content 3'),
        ),
        migrations.AlterField(
            model_name='about',
            name='aboutTitle',
            field=models.CharField(default='About Us', max_length=100, verbose_name='About Us Title'),
        ),
        migrations.AlterField(
            model_name='call',
            name='phone_number',
            field=models.TextField(max_length=100, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.TextField(max_length=100, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyrightText',
            field=models.TextField(max_length=100, verbose_name='Copyright text'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebookLink',
            field=models.TextField(max_length=100, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footerBody',
            field=models.CharField(default='Fresh and Delicious Ethiopian Food just for you!', max_length=200, verbose_name='Restaurant Motto'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footerTitle',
            field=models.CharField(default="El Deliciós d'Etiopia", max_length=100, verbose_name='Restaurant name'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagramLink',
            field=models.TextField(max_length=100, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='linkedinLink',
            field=models.TextField(max_length=100, verbose_name='LinkedIn Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitterLink',
            field=models.TextField(max_length=100, verbose_name='Twitter Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='year',
            field=models.TextField(default='2021', max_length=100, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='restaurantMotto',
            field=models.TextField(default='Fresh and Delicious Ethiopian Food just for you!', verbose_name='Restaurant Motto'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='restaurantName',
            field=models.CharField(default="El Deliciós d'Etiopia", max_length=100, verbose_name='Restaurant name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='avenue',
            field=models.CharField(max_length=200, verbose_name='Avenue'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekdays_endTime',
            field=models.CharField(max_length=100, verbose_name='Weekdays closing time'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekdays_startTime',
            field=models.CharField(max_length=100, verbose_name='Weekdays opening time'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekends_endTime',
            field=models.CharField(max_length=100, verbose_name='Weekends closing time'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekends_startTime',
            field=models.CharField(max_length=100, verbose_name='Weekends opening time'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUs1',
            field=models.CharField(default='', max_length=100, verbose_name='Title 1'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUs2',
            field=models.CharField(default='', max_length=100, verbose_name='Title 2'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUs3',
            field=models.CharField(default='', max_length=100, verbose_name='Title 3'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUsDesc1',
            field=models.TextField(default='', verbose_name='Content 1'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUsDesc2',
            field=models.TextField(default='', verbose_name='Content 2'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUsDesc3',
            field=models.TextField(default='', verbose_name='Content 3'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='whyUsTitle',
            field=models.CharField(default='Why choose our restaurant', max_length=100, verbose_name='Why Us title'),
        ),
    ]
