# Generated by Django 3.0.5 on 2021-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20210326_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='weekdays_endTime',
            field=models.CharField(max_length=100, verbose_name='Weekdays Closing time'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekdays_startTime',
            field=models.CharField(max_length=100, verbose_name='Weekdays Opening time'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekends_endTime',
            field=models.CharField(max_length=100, verbose_name='Weekends Closing time'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='weekends_startTime',
            field=models.CharField(max_length=100, verbose_name='Weekends Opening time'),
        ),
    ]
