# Generated by Django 3.1.7 on 2021-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20210326_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialName', models.CharField(max_length=100, verbose_name='Special Food Name')),
                ('specialDescription', models.TextField(verbose_name='Special Description')),
                ('specialImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
