# Generated by Django 3.0.5 on 2021-03-26 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20210326_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_subject', models.TextField(max_length=100, verbose_name='Name')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating out of 5')),
                ('content', models.TextField(verbose_name='Testimonial Content')),
            ],
        ),
    ]
