# Generated by Django 3.0.5 on 2021-03-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
