# Generated by Django 3.0.5 on 2021-03-26 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20210326_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating')),
                ('content', models.TextField(verbose_name='Rating')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Rating'),
        ),
    ]
