# Generated by Django 3.0.5 on 2021-03-26 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_auto_20210326_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating'),
        ),
    ]
