# Generated by Django 3.0.5 on 2021-03-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20210326_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default=5, verbose_name='Testimonial Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Rating'),
        ),
    ]
