# Generated by Django 3.0.5 on 2021-03-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_auto_20210326_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
    ]
