# Generated by Django 3.0.5 on 2021-03-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_remove_rating_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.TextField(max_length=100, verbose_name='Title')),
                ('price', models.TextField(max_length=100, verbose_name='Event Price')),
                ('content', models.TextField(verbose_name='Events Content')),
            ],
        ),
    ]
