# Generated by Django 3.0.5 on 2021-03-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20210326_1537'),
        ('restaurant', '0019_special'),
    ]

    operations = [
    ]
