# Generated by Django 3.1.7 on 2021-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_merge_20210326_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventImage',
            field=models.ImageField(default=' ', upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
