# Generated by Django 3.1.7 on 2021-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_event_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefName', models.CharField(max_length=100, verbose_name="Chef's Name")),
                ('chefRole', models.CharField(max_length=100, verbose_name="Chef's Role")),
                ('chefImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
