# Generated by Django 3.0.5 on 2021-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_chefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterLink', models.TextField(max_length=100, verbose_name='Twitter Link')),
                ('facebookLink', models.TextField(max_length=100, verbose_name='Facebook Link')),
                ('instagramLink', models.TextField(max_length=100, verbose_name='Instagram Link')),
                ('linkedinLink', models.TextField(max_length=100, verbose_name='LinkedIn Link')),
                ('whatsappLink', models.TextField(max_length=100, verbose_name='WhatsApp Link')),
                ('telegramLink', models.TextField(max_length=100, verbose_name='Telegram Link')),
            ],
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facebookLink',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagramLink',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedinLink',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='twitterLink',
        ),
    ]
