# Generated by Django 3.0.5 on 2021-03-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_auto_20210328_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
