# Generated by Django 3.0.5 on 2021-03-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_auto_20210328_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chefs',
            new_name='Chef',
        ),
        migrations.RenameModel(
            old_name='OpenHours',
            new_name='OpeningHour',
        ),
    ]
