# Generated by Django 3.0.5 on 2021-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0033_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dessertItems', models.ManyToManyField(blank=True, related_name='order', to='restaurant.DessertMenu')),
                ('drinkItems', models.ManyToManyField(blank=True, related_name='order', to='restaurant.DrinksMenu')),
                ('mainItems', models.ManyToManyField(blank=True, related_name='order', to='restaurant.MainMenu')),
                ('starterItems', models.ManyToManyField(blank=True, related_name='order', to='restaurant.StarterMenu')),
            ],
        ),
    ]
