# Generated by Django 3.0.5 on 2021-03-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_category_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='location',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
