# Generated by Django 3.0.5 on 2021-04-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_auto_20210331_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='specialImage',
        ),
    ]
