# Generated by Django 3.0.5 on 2021-04-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_remove_special_specialimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='chefImage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventImage',
        ),
    ]
