# Generated by Django 3.1.7 on 2021-04-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_auto_20210412_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
